name: MLFlow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: heart-disease-env
          auto-activate-base: false

      - name: Run MLflow Project
        run: conda run -n heart-disease-env mlflow run MLProject

