name: Train ML Model with MLflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install mlflow pandas scikit-learn numpy joblib

    - name: Run MLflow project
      run: |
        mlflow run MLProject --env-manager=local -P dataset_path=heart_clean.csv
